### PR TITLE
emodbus compatible for ESP32 ethernet using Wiznet W5500

### PR DESCRIPTION
**Pull request by OptifySudarshanPatil**

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi, @cnSchwarzer and @maxgerhardt.

Can you please sign the CLA?
https://cla-assistant.io/arduino-libraries/Ethernet?pullRequest=214

**Comment by maxgerhardt** [comment]
All done.

**Comment by OptifySudarshanPatil** [comment]
Closing pull request because of unknown "Schwarzer" user pending CLA

**Comment by cnSchwarzer** [comment]
Sorry, I have no recollection that I'm part of this. But I have some memory that I wrote https://github.com/arduino-libraries/Ethernet/pull/214/commits/81c2ce0c6922fc984703bf3adeacaf73bcc3f578
I also signed the CLA.

**Comment by OptifySudarshanPatil** [comment]
> Sorry, I have no recollection that I'm part of this. But I have some memory that I wrote [81c2ce0](https://github.com/arduino-libraries/Ethernet/commit/81c2ce0c6922fc984703bf3adeacaf73bcc3f578) I also signed the CLA.

Hey!
Thanks update.
The Issue was from my side to open pull request with external modification. I've opened another PR with clean commit. #255

**Pull request closed without merging**
