### PR TITLE
Ethernet: Add support for Controllino SPI CS

### PR DESCRIPTION
**Pull request by jpirko**
Signed-off-by: Jiri Pirko <jiri@resnulli.us>

### CODE REVIEW

**Comment by jpirko** [comment]
Anything I can do to get this one merged? Thanks!

**Comment by PaulStoffregen** [comment]
The plan is to replace all this code.  See issue #37.

The new pin config code will looks like this:

    #if defined(__AVR__)
    #define SS_PIN_DEFAULT  10
    #elif defined(PIN_SPI_SS)
    #define SS_PIN_DEFAULT  PIN_SPI_SS
    #elif defined(CORE_SS0_PIN)
    #define SS_PIN_DEFAULT  CORE_SS0_PIN
    #else
    #define SS_PIN_DEFAULT  10
    #endif

A special case can be added, if port J pin 3 does not correspond to pin 10.

**Comment by PaulStoffregen** [comment]
I'm looking at the Controllino variant pins_arduino.h.  It seems they do not define a digital pin number for port J pin 3.  That will be a problem.

**Comment by jpirko** [comment]
I'm not that familiar with the code. What do you suggest to do?

**Comment by jpirko** [comment]
Any news here? Could this be merged or resolved in different way please?

**Comment by PaulStoffregen** [comment]
Version 2.0.0 will have Ethernet.init(cspin).  The pin for CS must have a digital pin number.

**Comment by TimoErdmann** [comment]
So Version 2.0 is released and is also available on the Arduino Git.

I have inspected you code. The line. Ethernet.begin() calls W5100.init()

`uint8_t W5100Class::init(void)
{
	static bool initialized = false;
	uint8_t i;

	if (initialized) return 1;

	// Many Ethernet shields have a CAT811 or similar reset chip
	// connected to W5100 or W5200 chips.  The W5200 will not work at
	// all, and may even drive its MISO pin, until given an active low
	// reset pulse!  The CAT811 has a 240 ms typical pulse length, and
	// a 400 ms worst case maximum pulse length.  MAX811 has a worst
	// case maximum 560 ms pulse length.  This delay is meant to wait
	// until the reset pulse is ended.  If your hardware has a shorter
	// reset time, this can be edited or removed.
	delay(560);
	//Serial.println("w5100 init");

	SPI.begin();
	initSS();
	resetSS();
	SPI.beginTransaction(SPI_ETHERNET_SETTINGS);
...`

This calls intSS() and resetSS():
`#if defined(__AVR__)
	static volatile uint8_t *ss_pin_reg;
	static uint8_t ss_pin_mask;
	inline static void initSS() {
		ss_pin_reg = portOutputRegister(digitalPinToPort(ss_pin));
		ss_pin_mask = digitalPinToBitMask(ss_pin);
		pinMode(ss_pin, OUTPUT);
	}
	inline static void setSS() {
		*(ss_pin_reg) &= ~ss_pin_mask;
	}
	inline static void resetSS() {
		*(ss_pin_reg) |= ss_pin_mask;
	}`

So it will look for the Register. And manipulate them directly. If we no change the code to the suggested in this commit. I think this will function properly or?

`  #if defined(__AVR__)
     #if defined(CONTROLLINO_MAXI) || defined(CONTROLLINO_MEGA) || defined(CONTROLLINO_MAXI_AUTOMATION)
       inline static void initSS()    { DDRJ  |=  _BV(3);
                                        DDRJ  |=  _BV(2);
                                        PORTJ &=  _BV(2); };
       inline static void setSS()     { PORTJ &= ~_BV(3); };
       inline static void resetSS()   { PORTJ |=  _BV(3); };
     #elif defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)`

I could check the functionality on Monday or Tuesday. I will reply to this when I've validated this.

**Comment by PaulStoffregen** [comment]
> I think this will function properly or?
>
>    inline static void initSS() { DDRJ |= _BV(3); DDRJ |= _BV(2); PORTJ &= _BV(2); }; inline static void setSS() { PORTJ &= ~_BV(3); }; inline static void resetSS() { PORTJ |= _BV(3); }; 

No, this is not the proper way.  I will not accept this change to the 2.0.0 library.

Use the digital pin number for that pin.  If there is no digital pin number, then update the Controllino board support package.

**Comment by PaulStoffregen** [comment]
I also recommend adding a define to Controllino's variant.h or pins_arduino.h to define PIN_SPI_SS_ETHERNET_LIB.  Look at the code near the top of w5100.h.

https://github.com/arduino-libraries/Ethernet/blob/master/src/utility/w5100.cpp#L16

**Comment by PaulStoffregen** [comment]
I've created an issue with Controllino to ask them to update their board support library.

https://github.com/CONTROLLINO-PLC/CONTROLLINO_Library/issues/20

**Comment by PaulStoffregen** [comment]
Controllino has updated their board support library for compatibility with Ethernet 2.0.0.

**Pull request closed without merging**
